# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Hi, I'm Arlin Cherian"
email: "arlin.mary95@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  "I'm an upcoming data scientist based in Vancouver, Canada. I am a Master of 
  Data Science candidate at the University of British Columbia, Vancouver. I have 
  over 3 years of experience in data analytics, epidemiology research and scientific publication.
  I am fascinated with the applications of data science in various domains such as healthcare."
  
twitter_username: "@Carlyle_95"
github_username: "@arlincherian"
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Arlin Cherian"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : """Data Scientist\n
  Epidemiologist"""
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/arlin-cherian-37133ba4/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Carlyle_95"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/arlincherian"


footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Carlyle_95"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/arlincherian"


defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
    # _projects
  - scope:
      path: "_pages"
      type: projects
    values:
      layout: single
      author_profile: true
  

publication_archive:
  type: liquid
  path: /publications/
posts_archive:
  type: liquid
  path: /posts/
